#!/usr/bin/env python3
from pulsectl import Pulse, pulsectl
from simple_term_menu import TerminalMenu
from sys import argv
from getopt import getopt, GetoptError
from re import compile

# Interactive Menu Variables
# Max length of description field in menu
MAX_LENGTH = 22
# Number of words to pull out from description
WORD_COUNT = 2
# --------------------------


# Prints help
def help():
    print("Usage: {0} [OPTION] [SINK_NAME]\n"
          "Moves default sink to SINK_NAME, accepts partial or full SINK_NAME.\n"
          "\n"
          "-h, --help\n\tThis dialog.\n"
          "-l, --list\n\tList available sink names\n"
          "-i, --interactive\n\tInteractive sink selection".format(argv[0].split("/")[-1]))
    exit(1)


def prompt_user(sink_list, default_sink_name):
    items = []
    default_idx = 0
    for i in range(len(sink_list)):
        if(sink_list[i].name == default_sink_name):
            default_idx = i

        desc = sink_list[i].description
        friendly_desc = " ".join(desc.split(" ")[:WORD_COUNT])
        items.append(friendly_desc[:MAX_LENGTH])
    return sink_list[TerminalMenu(items, cursor_index=default_idx,menu_cursor_style=("fg_blue", "bold")).show()]
    

# Attempts to derive a sink object using a user provided (sub)string of the sinks name
def parse_remainder(argv, remainder):
    sink_search = None
    # Check there is only one trailing argument
    if len(argv) == 2:
        sink_search = remainder[0]
    elif len(argv) > 2:
        print("Too many arguments\n")
        help()

    if sink_search is not None:
        # returns a list of objects that match the sink_search query
        sink = list(filter(lambda s: sink_search in s.name, sink_list))

        # Return the first item from the search if the list isn't empty
        if len(sink) == 0:
            print("Could not find a sink matching {}".format(sink_search))
            exit(2)
        else:
            return sink[0]
    else:
        print("Not enough arguments\n")
        help()


try:
    options, remainder = getopt(argv[1:], 'ilh', ['interactive', 'list', 'help'])
except GetoptError:
    help()

# Open a pulse client session, name is arbitrary so just pass script name
with Pulse(argv[0]) as pulse:
    sink = None
    sink_list = pulse.sink_list()
    default_sink_name = pulse.server_info().default_sink_name

    # Process command line options
    for opt, arg in options:
        if opt in ('-l', '--list'):
            for sink in sink_list:
                print(sink.name)
            exit(0)
        elif opt in ('-h', '--help'):
            help()
        elif opt in ('-i', '--interactive'):
            sink = prompt_user(sink_list, default_sink_name)
        else:
            help()

    # If have made it out of options loop and still don't have a sink,
    # we should try and generate on from any trailing arguments
    if sink is None:
        sink = parse_remainder(argv, remainder)

    # Try and move sink
    try:
        # Set new sink as default
        pulse.sink_default_set(sink)

        # Each previously 'seen' application has a linked stream_restore object that stores its default sink,
        # each of these objects must be pointed to our new default sink for it to truly become the default
        for stream in pulse.stream_restore_list():
            # Duplicate the stream_restore object
            new_stream = stream
            # Change device to our new sink
            new_stream.device = sink.name
            # Delete old object from storage
            pulse.stream_restore_delete(stream)
            # Store our new object with correct sink
            pulse.stream_restore_write(new_stream)

        # Currently active inputs must be moved to the new sink
        for sink_input in pulse.sink_input_list():
            pulse.sink_input_move(sink_input.index, sink.index)

    except pulsectl.PulseOperationFailed:
        print("Unable to move sink to {}".format(sink.description))
